### ISSUE TITLE
有时候会出现跳月

### ISSUE THREAD

**Issue by cat-kun** [DMQ/calendar#2]
点击 左右箭头选择月份的时候，会出现跳月
![bug](http://7xon9l.com1.z0.glb.clouddn.com/calendar.gif)

**Comment by DMQ** [comment]
@dengxiaozhen 感谢反馈，这是zepto的bug，在chrome55版本后，tap事件会触发两次，是因为chrom55版本后加入了pointer事件，已通过修正zepto.min.js解决！
