### ISSUE TITLE
点击当前月份的显示的前几天

### ISSUE THREAD

**Issue by cat-kun** [DMQ/calendar#4]
目前有个需求，就是点击当前月的 “上个月几天”，或者 “下个月几天”也要能打印 “年月日”。求大神指点

![](http://ww1.sinaimg.cn/large/84295ee1gy1fg7y6xiasaj207t07emyn.jpg)

类似这个网站 http://www.vvic.com/new/2017-05-04

![](http://ww1.sinaimg.cn/large/84295ee1gy1fg7y9ex8lbg208606haj3.gif)

**Comment by DMQ** [comment]
看了一下，基本是一样的，我这个组件在`onChangeMonth`回调里面就能监听到，并不需要在切换了月之后还要点击一次
这里点击头部的 `<` , `>` 切换月和点击上下个月的几天切换月，没有本质区别，都会在`onChangeMonth`里面监听到

**Comment by DMQ** [comment]
@dengxiaozhen 另外，欢迎fork项目，可以根据你的实际需求修改源码，提pr，完善该组件，增加更多的功能，例如：点击年月可以下拉选择年和月等，我自认为这个小组件的源码还是比较清晰易懂的

**Comment by cat-kun** [comment]
谢谢指点，我再研究下
