### ISSUE TITLE
是否可以支持左右手势操作

### ISSUE THREAD

**Issue by goldencolor** [DMQ/calendar#5]
是否可以支持左右手势操作？

**Comment by DMQ** [comment]
@goldencolor 不好意思，目前没有时间维护这个项目了。如果你需要手势操作，可以使用我的另一个项目来做 https://github.com/DMQ/mTouch
这里我提供一下思路：
1、再写一个js，继承calendar-extend-slide.js
2、现在是默认生成一个月的日历，你可以默认生成三个月份的数据按左（上一个月的日历，隐藏的）、中（当前月的日历，显示的）、右（下一个月的日历，隐藏的）的位置放好，生成日历视图的方法是`calendar.js` 中的 `tplCalendar` 方法，传入年月日即可
3、使用 `mTouch` 的 `swiping` 来绑定左右滑动的手势，对日历的整体做一个跟随手指移动的位移，使用 `swipeleft`和`swiperight` 来切换上下月，在切换完之后，再调整一下三个月份的数据，保持这样的视图：左（上一个月的日历，隐藏的）、中（当前月的日历，显示的）、右（下一个月的日历，隐藏的）

如果还有疑问的话可以在这条issue交流

**Comment by goldencolor** [comment]
不知道你看过钉钉那个日历吗？如果有可能希望搞成那样的可付费定制下~

**Comment by DMQ** [comment]
@goldencolor 嗯，看了下，就是少了左右切换月份的功能，上下折叠的功能是支持的，只是demo中是一个按钮，没有绑定手势，按照我给的思路是完全可以实现的

**Comment by goldencolor** [comment]
@DMQ 有没可能实现vue 上述功能啊。。。实在对这这块不是很熟悉 还是你来的比较快啊~~点赞啊~~打CALL啊

**Comment by DMQ** [comment]
Vue做也是可以的，思路都一样。不过我目前确实没时间哈，很抱歉
