### ISSUE TITLE
日历切换月份的时候怎么改变日历上的标记tagDates

### ISSUE THREAD

**Issue by shihang1228** [DMQ/calendar#6]

**Comment by DMQ** [comment]
方式一：可以在onChangeMonthBefore这个回调里面使用this.set('tagDates', tagDates)来设置新的标记，但是如果你是要根据下一个月的年月日数据才能确定tagDates的场景下这种方式不适用，因为onChangeMonthBefore回调传回来的是没切换月之前的年月日
方式二：初始化日历时不要传入tagDates，在onChangeMonth回调里面调用this.takeTages(tagDates)来打标记
方式二更适合各种场景

**Comment by DMQ** [comment]
更正：this.takeTages 应该改为 this.takeTags

**Comment by shihang1228** [comment]
谢谢啦

**Comment by shihang1228** [comment]
您好，遇到一个问题，在日历中填充标记时，本来应该标记下个月的5号，但是后台送过来的格式是[18,19,5]，标记在日历中却把当月的5号标记上了，这个要怎么解决

![_20180116165750](https://user-images.githubusercontent.com/6914201/34980216-b39ac346-fa9b-11e7-8b25-44394ce934ab.png)

**Comment by DMQ** [comment]
这种情况暂时没办法解决，目前只支持当前月份的标记，需要标记下一个月的日期得改一下源码

**Comment by shihang1228** [comment]
这个改起来困难吗？能不能提供一下思路要怎么改，主要改哪个地方

**Comment by DMQ** [comment]
改这个方法，现在只是找'.date'当前月的，可以判断一下你的标记是上一月或下一月，找'.pre'或'.next'的来添加标记
![image](https://user-images.githubusercontent.com/6860287/34980754-6ad922e8-fae0-11e7-890d-3efe54247ff2.png)

**Comment by shihang1228** [comment]
判断标记是上个月还是下个月还是当前月，现在这个tags标记数组[18,19,5]可以改成[{"date":18,"bj":"now"},{"date":19,"bj":"now"},{"date":5,"bj":"next"}]吗？还是标记数组格式不变，js通过其他方法也能判断出是上个月还是下个月？

**Comment by DMQ** [comment]
这个得你自己去判断了，提供个思路，遍历标记数据，直到一个数字比上一个小，那么就可以认定，从这个数字开始就是下一个月的日期

**Comment by shihang1228** [comment]
我也想过这个办法，但是不行，如果后台送过来的是【1,2】，这样便无法判断出是当月的1号和2号还是下个月的1号和2号。我现在想把标记数组的格式变成上面的二维数组的样子，但不知道对源码的哪些地方有影响？

**Comment by DMQ** [comment]
你看一下源码，不复杂的，takeTags这个方法就是找到对应日期的dom节点添加一个class，只是现在没有处理上一个月和下一个月的日期，当前月的日期dom节点class是.date,上一个月和下一月的分别是.pre, .next，你区分一下处理就行了
